import React from "react"
import { ArrowRight } from "lucide-react"

// Types match our backend/frontend angle options
export type FaceExampleType =
    | "front" | "left" | "right"
    | "upward" | "downward"
    | "glasses" | "hat"
    | "lighting" | "smile"
    | "other"

// Since file names generated by the AI end with timestamps, we just matched the beginning
// You will need to rename the files in `public/examples` to exactly match these, or
// update these paths to match the exact generated filenames.
// For now, I will use exact filenames since we copied them.

const EXAMPLE_MAP: Record<FaceExampleType, { src: string; caption: string; instruction: string }> = {
    front: {
        src: "/examples/front_face_example_1772863764375.png",
        caption: "Front View",
        instruction: "Look directly at the camera. Keep your expression neutral."
    },
    left: {
        src: "/examples/left_face_example_1772863780959.png",
        caption: "Left Profile",
        instruction: "Turn your head clearly to your left side. Your left profile should be visible."
    },
    right: {
        src: "/examples/right_face_example_1772863809424.png",
        caption: "Right Profile",
        instruction: "Turn your head clearly to your right side. Your right profile should be visible."
    },
    upward: {
        src: "/examples/upward_face_example_1772863823377.png",
        caption: "Looking Upward",
        instruction: "Tilt your head upwards as if looking at the ceiling."
    },
    downward: {
        src: "/examples/downward_face_example_1772863841519.png",
        caption: "Looking Downward",
        instruction: "Tilt your head down towards the floor."
    },
    glasses: {
        src: "/examples/glasses_face_example_1772863856700.png",
        caption: "Wearing Glasses",
        instruction: "Wear thick or dark sunglasses. Look straight at the camera."
    },
    hat: {
        src: "/examples/hat_face_example_1772863887101.png",
        caption: "Wearing Hat",
        instruction: "Wear a cap or hat. Make sure your face is still visible."
    },
    lighting: {
        src: "/examples/dim_face_example_1772863903241.png",
        caption: "Dim Lighting",
        instruction: "Take a photo in a room with very low or moody lighting."
    },
    smile: {
        src: "/examples/smile_face_example_1772863927552.png",
        caption: "Smiling Face",
        instruction: "Smile broadly showing your teeth at the camera."
    },
    other: {
        src: "/examples/front_face_example_1772863764375.png",
        caption: "Base Reference",
        instruction: "Look directly into the camera."
    }
}

interface VisualFaceExampleProps {
    type: FaceExampleType
    className?: string
}

export function VisualFaceExample({ type, className = "" }: VisualFaceExampleProps) {
    const data = EXAMPLE_MAP[type] || EXAMPLE_MAP.front

    return (
        <div className={`flex flex-col sm:flex-row bg-slate-50 border border-slate-200 rounded-2xl overflow-hidden shadow-sm ${className}`}>
            {/* Image Side */}
            <div className="w-full sm:w-40 h-48 sm:h-auto shrink-0 bg-slate-200 relative">
                <img
                    src={data.src}
                    alt={data.caption}
                    className="w-full h-full object-cover"
                />
                <div className="absolute inset-0 bg-gradient-to-t from-black/60 via-transparent to-transparent sm:hidden" />
                <div className="absolute bottom-2 left-3 sm:hidden">
                    <span className="text-white text-xs font-bold bg-black/40 px-2 py-1 rounded-md backdrop-blur-sm">
                        Example
                    </span>
                </div>
            </div>

            {/* Instruction Side */}
            <div className="p-4 sm:p-5 flex flex-col justify-center flex-1">
                <div className="hidden sm:inline-block mb-2">
                    <span className="text-[#0ea5e9] text-[10px] uppercase font-bold tracking-wider bg-[#0ea5e9]/10 px-2.5 py-1 rounded-full">
                        Reference Photo
                    </span>
                </div>
                <h3 className="text-sm font-bold text-slate-800 mb-1">{data.caption}</h3>
                <p className="text-xs text-slate-600 leading-relaxed max-w-[280px]">
                    {data.instruction}
                </p>
                <div className="mt-3 flex items-center gap-1.5 text-xs font-medium text-slate-500">
                    <ArrowRight className="w-3.5 h-3.5" /> Match this pose for the best result
                </div>
            </div>
        </div>
    )
}
